:bug: Fix bug of editing and adding bookmarks
Cleymax/BookmarksBox pull request #26
Opened 2021-05-16 09:08 UTC by Zerka30

2021-05-16 12:12 UTC, Cleymax commented on app/controllers/BookmarkController.php
> +            $this->render(View::new('dashboard'), 'Accueil', ['data' => $data ?? []]);
#25  
Trop de répétition.

2021-05-16 12:12 UTC, Cleymax commented on app/controllers/BookmarkController.php
>          }elseif(array_key_exists("delete", $_POST)){
Pas du tout opti  #25

2021-05-16 12:13 UTC, Cleymax commented on resources/views/dashboard.php
> +<button class="btn btn-green" aria-label="edit" title="edit"  onclick="add(this)" name="edit" id="btn-add" style="margin-right: 5px;"><span class="material-icons">add</span> Ajouter</button>
aria-label, title en français

2021-05-16 12:16 UTC, Cleymax requested changes
Regarder #25 vraiment.

2021-05-20 19:43 UTC, Cleymax commented
Need ! @Zerka30

2021-05-21 20:01 UTC, Cleymax commented on app/controllers/BookmarkController.php
> +use http\Exception\InvalidArgumentException;
Problème d'import

2021-05-21 20:01 UTC, Cleymax commented on app/controllers/BookmarkController.php
> +        $action = htmlspecialchars($_POST['action']);
Bien ! ;)

2021-05-21 20:02 UTC, Cleymax commented on app/controllers/BookmarkController.php
> +                    $response = $this->Bookmarks->add($_POST["bookmarks-modal"], $_POST["link-modal"], $_POST["thumbnail-modal"], $_POST["difficulty-modal"]);
Il manque des check pour `bookmarks-modal` et `difficulty-modal`

2021-05-21 20:04 UTC, Cleymax commented on app/controllers/DashboardController.php
> +            $teams = $this->Teams->getAllForMe();
Bien !

2021-05-21 20:07 UTC, Cleymax commented on app/models/Bookmarks.php
> +    }
Ya un soucis de nom de table

2021-05-21 20:08 UTC, Cleymax commented on app/models/Bookmarks.php
> +            ->params([Auth::User()->id, $id]);
Pk un U majuscule

2021-05-21 20:08 UTC, Cleymax commented on app/models/Bookmarks.php
> +            ->params([Auth::User()->id, $id])
Pareil que https://github.com/Cleymax/BookmarksBox/pull/26/files/3d22f2da1872e9ecd4c307fe4f60e788bddba27a..41bac6acbc11d19a14521434219b017666c6a373#r637202742

2021-05-21 20:09 UTC, Cleymax commented on resources/scss/page/_home.scss
>  }
Des règles globales dans un fichier qui se trouve dans le dossier page

2021-05-21 20:23 UTC, Zerka30 commented on app/controllers/BookmarkController.php
> +use http\Exception\InvalidArgumentException;
?

2021-05-24 09:47 UTC, Cleymax approved these changes

2021-05-24 10:59 UTC, merged